# Generated by Django 5.1.3 on 2024-12-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='body',
        ),
    ]
